name: CI

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Run a one-line script
      run: echo Hello, world!
    - name: validate-license-action
      uses: datreeio/validate-license-action@v1.0.0
    #  continue-on-error: true
    #  timeout-minutes: 30
    #  id: hello
    #- name: Run a multi-line script
    #  run: |
    #    echo Add other actions to build,
    #    echo test, and deploy your project.
        #    - name: package
        #run: |
        #tar -czf vim.tar.gz screenshots .vim .vimrc README.md
#     - name: Upload release
#       uses: yakuhzi/action-release@v1
#       with:
#         file: vim.tar.gz
#         #changelog: /path/to/CHANGELOG.txt
#       env:
#         GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
